//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MyBlackBoxCore
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class myblackboxcoreEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new myblackboxcoreEntities object using the connection string found in the 'myblackboxcoreEntities' section of the application configuration file.
        /// </summary>
        public myblackboxcoreEntities() : base("name=myblackboxcoreEntities", "myblackboxcoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new myblackboxcoreEntities object.
        /// </summary>
        public myblackboxcoreEntities(string connectionString) : base(connectionString, "myblackboxcoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new myblackboxcoreEntities object.
        /// </summary>
        public myblackboxcoreEntities(EntityConnection connection) : base(connection, "myblackboxcoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<note> notes
        {
            get
            {
                if ((_notes == null))
                {
                    _notes = base.CreateObjectSet<note>("notes");
                }
                return _notes;
            }
        }
        private ObjectSet<note> _notes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<note_doc> note_doc
        {
            get
            {
                if ((_note_doc == null))
                {
                    _note_doc = base.CreateObjectSet<note_doc>("note_doc");
                }
                return _note_doc;
            }
        }
        private ObjectSet<note_doc> _note_doc;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<note_key> note_key
        {
            get
            {
                if ((_note_key == null))
                {
                    _note_key = base.CreateObjectSet<note_key>("note_key");
                }
                return _note_key;
            }
        }
        private ObjectSet<note_key> _note_key;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<note_key_include> note_key_include
        {
            get
            {
                if ((_note_key_include == null))
                {
                    _note_key_include = base.CreateObjectSet<note_key_include>("note_key_include");
                }
                return _note_key_include;
            }
        }
        private ObjectSet<note_key_include> _note_key_include;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<note_sharing> note_sharing
        {
            get
            {
                if ((_note_sharing == null))
                {
                    _note_sharing = base.CreateObjectSet<note_sharing>("note_sharing");
                }
                return _note_sharing;
            }
        }
        private ObjectSet<note_sharing> _note_sharing;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<translation> translations
        {
            get
            {
                if ((_translations == null))
                {
                    _translations = base.CreateObjectSet<translation>("translations");
                }
                return _translations;
            }
        }
        private ObjectSet<translation> _translations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<userapp> userapps
        {
            get
            {
                if ((_userapps == null))
                {
                    _userapps = base.CreateObjectSet<userapp>("userapps");
                }
                return _userapps;
            }
        }
        private ObjectSet<userapp> _userapps;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the notes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonotes(note note)
        {
            base.AddObject("notes", note);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the note_doc EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonote_doc(note_doc note_doc)
        {
            base.AddObject("note_doc", note_doc);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the note_key EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonote_key(note_key note_key)
        {
            base.AddObject("note_key", note_key);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the note_key_include EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonote_key_include(note_key_include note_key_include)
        {
            base.AddObject("note_key_include", note_key_include);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the note_sharing EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonote_sharing(note_sharing note_sharing)
        {
            base.AddObject("note_sharing", note_sharing);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the translations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotranslations(translation translation)
        {
            base.AddObject("translations", translation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the userapps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouserapps(userapp userapp)
        {
            base.AddObject("userapps", userapp);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myblackboxcoreModel", Name="note")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class note : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new note object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="iDUser">Initial value of the IDUser property.</param>
        public static note Createnote(global::System.Int32 id, global::System.Int32 iDUser)
        {
            note note = new note();
            note.ID = id;
            note.IDUser = iDUser;
            return note;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUser
        {
            get
            {
                return _IDUser;
            }
            set
            {
                if (_IDUser != value)
                {
                    OnIDUserChanging(value);
                    ReportPropertyChanging("IDUser");
                    _IDUser = StructuralObject.SetValidValue(value, "IDUser");
                    ReportPropertyChanged("IDUser");
                    OnIDUserChanged();
                }
            }
        }
        private global::System.Int32 _IDUser;
        partial void OnIDUserChanging(global::System.Int32 value);
        partial void OnIDUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, true, "Text");
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateTimeInserted
        {
            get
            {
                return _DateTimeInserted;
            }
            set
            {
                OnDateTimeInsertedChanging(value);
                ReportPropertyChanging("DateTimeInserted");
                _DateTimeInserted = StructuralObject.SetValidValue(value, "DateTimeInserted");
                ReportPropertyChanged("DateTimeInserted");
                OnDateTimeInsertedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateTimeInserted;
        partial void OnDateTimeInsertedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateTimeInsertedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateTimeLastMod
        {
            get
            {
                return _DateTimeLastMod;
            }
            set
            {
                OnDateTimeLastModChanging(value);
                ReportPropertyChanging("DateTimeLastMod");
                _DateTimeLastMod = StructuralObject.SetValidValue(value, "DateTimeLastMod");
                ReportPropertyChanged("DateTimeLastMod");
                OnDateTimeLastModChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateTimeLastMod;
        partial void OnDateTimeLastModChanging(Nullable<global::System.DateTime> value);
        partial void OnDateTimeLastModChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Rate
        {
            get
            {
                return _Rate;
            }
            set
            {
                OnRateChanging(value);
                ReportPropertyChanging("Rate");
                _Rate = StructuralObject.SetValidValue(value, "Rate");
                ReportPropertyChanged("Rate");
                OnRateChanged();
            }
        }
        private Nullable<global::System.Int32> _Rate;
        partial void OnRateChanging(Nullable<global::System.Int32> value);
        partial void OnRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JobCode
        {
            get
            {
                return _JobCode;
            }
            set
            {
                OnJobCodeChanging(value);
                ReportPropertyChanging("JobCode");
                _JobCode = StructuralObject.SetValidValue(value, true, "JobCode");
                ReportPropertyChanged("JobCode");
                OnJobCodeChanged();
            }
        }
        private global::System.String _JobCode;
        partial void OnJobCodeChanging(global::System.String value);
        partial void OnJobCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PhaseNo
        {
            get
            {
                return _PhaseNo;
            }
            set
            {
                OnPhaseNoChanging(value);
                ReportPropertyChanging("PhaseNo");
                _PhaseNo = StructuralObject.SetValidValue(value, "PhaseNo");
                ReportPropertyChanged("PhaseNo");
                OnPhaseNoChanged();
            }
        }
        private Nullable<global::System.Int32> _PhaseNo;
        partial void OnPhaseNoChanging(Nullable<global::System.Int32> value);
        partial void OnPhaseNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true, "Image");
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsPrivate
        {
            get
            {
                return _IsPrivate;
            }
            set
            {
                OnIsPrivateChanging(value);
                ReportPropertyChanging("IsPrivate");
                _IsPrivate = StructuralObject.SetValidValue(value, "IsPrivate");
                ReportPropertyChanged("IsPrivate");
                OnIsPrivateChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsPrivate;
        partial void OnIsPrivateChanging(Nullable<global::System.Boolean> value);
        partial void OnIsPrivateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserLockedBy
        {
            get
            {
                return _UserLockedBy;
            }
            set
            {
                OnUserLockedByChanging(value);
                ReportPropertyChanging("UserLockedBy");
                _UserLockedBy = StructuralObject.SetValidValue(value, true, "UserLockedBy");
                ReportPropertyChanged("UserLockedBy");
                OnUserLockedByChanged();
            }
        }
        private global::System.String _UserLockedBy;
        partial void OnUserLockedByChanging(global::System.String value);
        partial void OnUserLockedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AuditUser
        {
            get
            {
                return _AuditUser;
            }
            set
            {
                OnAuditUserChanging(value);
                ReportPropertyChanging("AuditUser");
                _AuditUser = StructuralObject.SetValidValue(value, true, "AuditUser");
                ReportPropertyChanged("AuditUser");
                OnAuditUserChanged();
            }
        }
        private global::System.String _AuditUser;
        partial void OnAuditUserChanging(global::System.String value);
        partial void OnAuditUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AuditDateTime
        {
            get
            {
                return _AuditDateTime;
            }
            set
            {
                OnAuditDateTimeChanging(value);
                ReportPropertyChanging("AuditDateTime");
                _AuditDateTime = StructuralObject.SetValidValue(value, "AuditDateTime");
                ReportPropertyChanged("AuditDateTime");
                OnAuditDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _AuditDateTime;
        partial void OnAuditDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnAuditDateTimeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myblackboxcoreModel", Name="note_doc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class note_doc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new note_doc object.
        /// </summary>
        /// <param name="iDNote">Initial value of the IDNote property.</param>
        /// <param name="iDUser">Initial value of the IDUser property.</param>
        /// <param name="docName">Initial value of the DocName property.</param>
        public static note_doc Createnote_doc(global::System.Int32 iDNote, global::System.Int32 iDUser, global::System.String docName)
        {
            note_doc note_doc = new note_doc();
            note_doc.IDNote = iDNote;
            note_doc.IDUser = iDUser;
            note_doc.DocName = docName;
            return note_doc;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDNote
        {
            get
            {
                return _IDNote;
            }
            set
            {
                if (_IDNote != value)
                {
                    OnIDNoteChanging(value);
                    ReportPropertyChanging("IDNote");
                    _IDNote = StructuralObject.SetValidValue(value, "IDNote");
                    ReportPropertyChanged("IDNote");
                    OnIDNoteChanged();
                }
            }
        }
        private global::System.Int32 _IDNote;
        partial void OnIDNoteChanging(global::System.Int32 value);
        partial void OnIDNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUser
        {
            get
            {
                return _IDUser;
            }
            set
            {
                if (_IDUser != value)
                {
                    OnIDUserChanging(value);
                    ReportPropertyChanging("IDUser");
                    _IDUser = StructuralObject.SetValidValue(value, "IDUser");
                    ReportPropertyChanged("IDUser");
                    OnIDUserChanged();
                }
            }
        }
        private global::System.Int32 _IDUser;
        partial void OnIDUserChanging(global::System.Int32 value);
        partial void OnIDUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DocName
        {
            get
            {
                return _DocName;
            }
            set
            {
                if (_DocName != value)
                {
                    OnDocNameChanging(value);
                    ReportPropertyChanging("DocName");
                    _DocName = StructuralObject.SetValidValue(value, false, "DocName");
                    ReportPropertyChanged("DocName");
                    OnDocNameChanged();
                }
            }
        }
        private global::System.String _DocName;
        partial void OnDocNameChanging(global::System.String value);
        partial void OnDocNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value, "Version");
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private Nullable<global::System.Int32> _Version;
        partial void OnVersionChanging(Nullable<global::System.Int32> value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateTimeLastMod
        {
            get
            {
                return _DateTimeLastMod;
            }
            set
            {
                OnDateTimeLastModChanging(value);
                ReportPropertyChanging("DateTimeLastMod");
                _DateTimeLastMod = StructuralObject.SetValidValue(value, "DateTimeLastMod");
                ReportPropertyChanged("DateTimeLastMod");
                OnDateTimeLastModChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateTimeLastMod;
        partial void OnDateTimeLastModChanging(Nullable<global::System.DateTime> value);
        partial void OnDateTimeLastModChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InternalDirRemote
        {
            get
            {
                return _InternalDirRemote;
            }
            set
            {
                OnInternalDirRemoteChanging(value);
                ReportPropertyChanging("InternalDirRemote");
                _InternalDirRemote = StructuralObject.SetValidValue(value, true, "InternalDirRemote");
                ReportPropertyChanged("InternalDirRemote");
                OnInternalDirRemoteChanged();
            }
        }
        private global::System.String _InternalDirRemote;
        partial void OnInternalDirRemoteChanging(global::System.String value);
        partial void OnInternalDirRemoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileNameLocal
        {
            get
            {
                return _FileNameLocal;
            }
            set
            {
                OnFileNameLocalChanging(value);
                ReportPropertyChanging("FileNameLocal");
                _FileNameLocal = StructuralObject.SetValidValue(value, true, "FileNameLocal");
                ReportPropertyChanged("FileNameLocal");
                OnFileNameLocalChanged();
            }
        }
        private global::System.String _FileNameLocal;
        partial void OnFileNameLocalChanging(global::System.String value);
        partial void OnFileNameLocalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ToSyncronize
        {
            get
            {
                return _ToSyncronize;
            }
            set
            {
                OnToSyncronizeChanging(value);
                ReportPropertyChanging("ToSyncronize");
                _ToSyncronize = StructuralObject.SetValidValue(value, "ToSyncronize");
                ReportPropertyChanged("ToSyncronize");
                OnToSyncronizeChanged();
            }
        }
        private Nullable<global::System.Boolean> _ToSyncronize;
        partial void OnToSyncronizeChanging(Nullable<global::System.Boolean> value);
        partial void OnToSyncronizeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myblackboxcoreModel", Name="note_key")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class note_key : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new note_key object.
        /// </summary>
        /// <param name="iDNote">Initial value of the IDNote property.</param>
        /// <param name="iDUser">Initial value of the IDUser property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static note_key Createnote_key(global::System.Int32 iDNote, global::System.Int32 iDUser, global::System.String name)
        {
            note_key note_key = new note_key();
            note_key.IDNote = iDNote;
            note_key.IDUser = iDUser;
            note_key.Name = name;
            return note_key;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDNote
        {
            get
            {
                return _IDNote;
            }
            set
            {
                if (_IDNote != value)
                {
                    OnIDNoteChanging(value);
                    ReportPropertyChanging("IDNote");
                    _IDNote = StructuralObject.SetValidValue(value, "IDNote");
                    ReportPropertyChanged("IDNote");
                    OnIDNoteChanged();
                }
            }
        }
        private global::System.Int32 _IDNote;
        partial void OnIDNoteChanging(global::System.Int32 value);
        partial void OnIDNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUser
        {
            get
            {
                return _IDUser;
            }
            set
            {
                if (_IDUser != value)
                {
                    OnIDUserChanging(value);
                    ReportPropertyChanging("IDUser");
                    _IDUser = StructuralObject.SetValidValue(value, "IDUser");
                    ReportPropertyChanged("IDUser");
                    OnIDUserChanged();
                }
            }
        }
        private global::System.Int32 _IDUser;
        partial void OnIDUserChanging(global::System.Int32 value);
        partial void OnIDUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false, "Name");
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Level
        {
            get
            {
                return _Level;
            }
            set
            {
                OnLevelChanging(value);
                ReportPropertyChanging("Level");
                _Level = StructuralObject.SetValidValue(value, "Level");
                ReportPropertyChanged("Level");
                OnLevelChanged();
            }
        }
        private Nullable<global::System.Int32> _Level;
        partial void OnLevelChanging(Nullable<global::System.Int32> value);
        partial void OnLevelChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myblackboxcoreModel", Name="note_key_include")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class note_key_include : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new note_key_include object.
        /// </summary>
        /// <param name="wordName">Initial value of the WordName property.</param>
        public static note_key_include Createnote_key_include(global::System.String wordName)
        {
            note_key_include note_key_include = new note_key_include();
            note_key_include.WordName = wordName;
            return note_key_include;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WordName
        {
            get
            {
                return _WordName;
            }
            set
            {
                if (_WordName != value)
                {
                    OnWordNameChanging(value);
                    ReportPropertyChanging("WordName");
                    _WordName = StructuralObject.SetValidValue(value, false, "WordName");
                    ReportPropertyChanged("WordName");
                    OnWordNameChanged();
                }
            }
        }
        private global::System.String _WordName;
        partial void OnWordNameChanging(global::System.String value);
        partial void OnWordNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ToInclude
        {
            get
            {
                return _ToInclude;
            }
            set
            {
                OnToIncludeChanging(value);
                ReportPropertyChanging("ToInclude");
                _ToInclude = StructuralObject.SetValidValue(value, "ToInclude");
                ReportPropertyChanged("ToInclude");
                OnToIncludeChanged();
            }
        }
        private Nullable<global::System.Boolean> _ToInclude;
        partial void OnToIncludeChanging(Nullable<global::System.Boolean> value);
        partial void OnToIncludeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myblackboxcoreModel", Name="note_sharing")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class note_sharing : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new note_sharing object.
        /// </summary>
        /// <param name="iDNote">Initial value of the IDNote property.</param>
        /// <param name="iDUserSharing">Initial value of the IDUserSharing property.</param>
        /// <param name="iDUser">Initial value of the IDUser property.</param>
        public static note_sharing Createnote_sharing(global::System.Int32 iDNote, global::System.Int32 iDUserSharing, global::System.Int32 iDUser)
        {
            note_sharing note_sharing = new note_sharing();
            note_sharing.IDNote = iDNote;
            note_sharing.IDUserSharing = iDUserSharing;
            note_sharing.IDUser = iDUser;
            return note_sharing;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDNote
        {
            get
            {
                return _IDNote;
            }
            set
            {
                if (_IDNote != value)
                {
                    OnIDNoteChanging(value);
                    ReportPropertyChanging("IDNote");
                    _IDNote = StructuralObject.SetValidValue(value, "IDNote");
                    ReportPropertyChanged("IDNote");
                    OnIDNoteChanged();
                }
            }
        }
        private global::System.Int32 _IDNote;
        partial void OnIDNoteChanging(global::System.Int32 value);
        partial void OnIDNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUserSharing
        {
            get
            {
                return _IDUserSharing;
            }
            set
            {
                if (_IDUserSharing != value)
                {
                    OnIDUserSharingChanging(value);
                    ReportPropertyChanging("IDUserSharing");
                    _IDUserSharing = StructuralObject.SetValidValue(value, "IDUserSharing");
                    ReportPropertyChanged("IDUserSharing");
                    OnIDUserSharingChanged();
                }
            }
        }
        private global::System.Int32 _IDUserSharing;
        partial void OnIDUserSharingChanging(global::System.Int32 value);
        partial void OnIDUserSharingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUser
        {
            get
            {
                return _IDUser;
            }
            set
            {
                if (_IDUser != value)
                {
                    OnIDUserChanging(value);
                    ReportPropertyChanging("IDUser");
                    _IDUser = StructuralObject.SetValidValue(value, "IDUser");
                    ReportPropertyChanged("IDUser");
                    OnIDUserChanged();
                }
            }
        }
        private global::System.Int32 _IDUser;
        partial void OnIDUserChanging(global::System.Int32 value);
        partial void OnIDUserChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myblackboxcoreModel", Name="translation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class translation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new translation object.
        /// </summary>
        /// <param name="groupControl">Initial value of the GroupControl property.</param>
        /// <param name="origin">Initial value of the Origin property.</param>
        public static translation Createtranslation(global::System.String groupControl, global::System.String origin)
        {
            translation translation = new translation();
            translation.GroupControl = groupControl;
            translation.Origin = origin;
            return translation;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GroupControl
        {
            get
            {
                return _GroupControl;
            }
            set
            {
                if (_GroupControl != value)
                {
                    OnGroupControlChanging(value);
                    ReportPropertyChanging("GroupControl");
                    _GroupControl = StructuralObject.SetValidValue(value, false, "GroupControl");
                    ReportPropertyChanged("GroupControl");
                    OnGroupControlChanged();
                }
            }
        }
        private global::System.String _GroupControl;
        partial void OnGroupControlChanging(global::System.String value);
        partial void OnGroupControlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Origin
        {
            get
            {
                return _Origin;
            }
            set
            {
                if (_Origin != value)
                {
                    OnOriginChanging(value);
                    ReportPropertyChanging("Origin");
                    _Origin = StructuralObject.SetValidValue(value, false, "Origin");
                    ReportPropertyChanged("Origin");
                    OnOriginChanged();
                }
            }
        }
        private global::System.String _Origin;
        partial void OnOriginChanging(global::System.String value);
        partial void OnOriginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EN
        {
            get
            {
                return _EN;
            }
            set
            {
                OnENChanging(value);
                ReportPropertyChanging("EN");
                _EN = StructuralObject.SetValidValue(value, true, "EN");
                ReportPropertyChanged("EN");
                OnENChanged();
            }
        }
        private global::System.String _EN;
        partial void OnENChanging(global::System.String value);
        partial void OnENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IT
        {
            get
            {
                return _IT;
            }
            set
            {
                OnITChanging(value);
                ReportPropertyChanging("IT");
                _IT = StructuralObject.SetValidValue(value, true, "IT");
                ReportPropertyChanged("IT");
                OnITChanged();
            }
        }
        private global::System.String _IT;
        partial void OnITChanging(global::System.String value);
        partial void OnITChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FR
        {
            get
            {
                return _FR;
            }
            set
            {
                OnFRChanging(value);
                ReportPropertyChanging("FR");
                _FR = StructuralObject.SetValidValue(value, true, "FR");
                ReportPropertyChanged("FR");
                OnFRChanged();
            }
        }
        private global::System.String _FR;
        partial void OnFRChanging(global::System.String value);
        partial void OnFRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DE
        {
            get
            {
                return _DE;
            }
            set
            {
                OnDEChanging(value);
                ReportPropertyChanging("DE");
                _DE = StructuralObject.SetValidValue(value, true, "DE");
                ReportPropertyChanged("DE");
                OnDEChanged();
            }
        }
        private global::System.String _DE;
        partial void OnDEChanging(global::System.String value);
        partial void OnDEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ES
        {
            get
            {
                return _ES;
            }
            set
            {
                OnESChanging(value);
                ReportPropertyChanging("ES");
                _ES = StructuralObject.SetValidValue(value, true, "ES");
                ReportPropertyChanged("ES");
                OnESChanged();
            }
        }
        private global::System.String _ES;
        partial void OnESChanging(global::System.String value);
        partial void OnESChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TypeControl
        {
            get
            {
                return _TypeControl;
            }
            set
            {
                OnTypeControlChanging(value);
                ReportPropertyChanging("TypeControl");
                _TypeControl = StructuralObject.SetValidValue(value, true, "TypeControl");
                ReportPropertyChanged("TypeControl");
                OnTypeControlChanged();
            }
        }
        private global::System.String _TypeControl;
        partial void OnTypeControlChanging(global::System.String value);
        partial void OnTypeControlChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myblackboxcoreModel", Name="userapp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class userapp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new userapp object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static userapp Createuserapp(global::System.Int32 id, global::System.String name)
        {
            userapp userapp = new userapp();
            userapp.ID = id;
            userapp.Name = name;
            return userapp;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Language
        {
            get
            {
                return _Language;
            }
            set
            {
                OnLanguageChanging(value);
                ReportPropertyChanging("Language");
                _Language = StructuralObject.SetValidValue(value, true, "Language");
                ReportPropertyChanged("Language");
                OnLanguageChanged();
            }
        }
        private global::System.String _Language;
        partial void OnLanguageChanging(global::System.String value);
        partial void OnLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDProfile
        {
            get
            {
                return _IDProfile;
            }
            set
            {
                OnIDProfileChanging(value);
                ReportPropertyChanging("IDProfile");
                _IDProfile = StructuralObject.SetValidValue(value, "IDProfile");
                ReportPropertyChanged("IDProfile");
                OnIDProfileChanged();
            }
        }
        private Nullable<global::System.Int32> _IDProfile;
        partial void OnIDProfileChanging(Nullable<global::System.Int32> value);
        partial void OnIDProfileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OldPassword
        {
            get
            {
                return _OldPassword;
            }
            set
            {
                OnOldPasswordChanging(value);
                ReportPropertyChanging("OldPassword");
                _OldPassword = StructuralObject.SetValidValue(value, true, "OldPassword");
                ReportPropertyChanged("OldPassword");
                OnOldPasswordChanged();
            }
        }
        private global::System.String _OldPassword;
        partial void OnOldPasswordChanging(global::System.String value);
        partial void OnOldPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegistryName
        {
            get
            {
                return _RegistryName;
            }
            set
            {
                OnRegistryNameChanging(value);
                ReportPropertyChanging("RegistryName");
                _RegistryName = StructuralObject.SetValidValue(value, true, "RegistryName");
                ReportPropertyChanged("RegistryName");
                OnRegistryNameChanged();
            }
        }
        private global::System.String _RegistryName;
        partial void OnRegistryNameChanging(global::System.String value);
        partial void OnRegistryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegistrySurname
        {
            get
            {
                return _RegistrySurname;
            }
            set
            {
                OnRegistrySurnameChanging(value);
                ReportPropertyChanging("RegistrySurname");
                _RegistrySurname = StructuralObject.SetValidValue(value, true, "RegistrySurname");
                ReportPropertyChanged("RegistrySurname");
                OnRegistrySurnameChanged();
            }
        }
        private global::System.String _RegistrySurname;
        partial void OnRegistrySurnameChanging(global::System.String value);
        partial void OnRegistrySurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegistryAddress
        {
            get
            {
                return _RegistryAddress;
            }
            set
            {
                OnRegistryAddressChanging(value);
                ReportPropertyChanging("RegistryAddress");
                _RegistryAddress = StructuralObject.SetValidValue(value, true, "RegistryAddress");
                ReportPropertyChanged("RegistryAddress");
                OnRegistryAddressChanged();
            }
        }
        private global::System.String _RegistryAddress;
        partial void OnRegistryAddressChanging(global::System.String value);
        partial void OnRegistryAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WorkGroup
        {
            get
            {
                return _WorkGroup;
            }
            set
            {
                OnWorkGroupChanging(value);
                ReportPropertyChanging("WorkGroup");
                _WorkGroup = StructuralObject.SetValidValue(value, true, "WorkGroup");
                ReportPropertyChanged("WorkGroup");
                OnWorkGroupChanged();
            }
        }
        private global::System.String _WorkGroup;
        partial void OnWorkGroupChanging(global::System.String value);
        partial void OnWorkGroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateRegistration
        {
            get
            {
                return _DateRegistration;
            }
            set
            {
                OnDateRegistrationChanging(value);
                ReportPropertyChanging("DateRegistration");
                _DateRegistration = StructuralObject.SetValidValue(value, "DateRegistration");
                ReportPropertyChanged("DateRegistration");
                OnDateRegistrationChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateRegistration;
        partial void OnDateRegistrationChanging(Nullable<global::System.DateTime> value);
        partial void OnDateRegistrationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, true, "ImagePath");
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Level
        {
            get
            {
                return _Level;
            }
            set
            {
                OnLevelChanging(value);
                ReportPropertyChanging("Level");
                _Level = StructuralObject.SetValidValue(value, true, "Level");
                ReportPropertyChanged("Level");
                OnLevelChanged();
            }
        }
        private global::System.String _Level;
        partial void OnLevelChanging(global::System.String value);
        partial void OnLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RateHour
        {
            get
            {
                return _RateHour;
            }
            set
            {
                OnRateHourChanging(value);
                ReportPropertyChanging("RateHour");
                _RateHour = StructuralObject.SetValidValue(value, "RateHour");
                ReportPropertyChanged("RateHour");
                OnRateHourChanged();
            }
        }
        private Nullable<global::System.Decimal> _RateHour;
        partial void OnRateHourChanging(Nullable<global::System.Decimal> value);
        partial void OnRateHourChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AuditUser
        {
            get
            {
                return _AuditUser;
            }
            set
            {
                OnAuditUserChanging(value);
                ReportPropertyChanging("AuditUser");
                _AuditUser = StructuralObject.SetValidValue(value, true, "AuditUser");
                ReportPropertyChanged("AuditUser");
                OnAuditUserChanged();
            }
        }
        private global::System.String _AuditUser;
        partial void OnAuditUserChanging(global::System.String value);
        partial void OnAuditUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AuditDateTime
        {
            get
            {
                return _AuditDateTime;
            }
            set
            {
                OnAuditDateTimeChanging(value);
                ReportPropertyChanging("AuditDateTime");
                _AuditDateTime = StructuralObject.SetValidValue(value, "AuditDateTime");
                ReportPropertyChanged("AuditDateTime");
                OnAuditDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _AuditDateTime;
        partial void OnAuditDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnAuditDateTimeChanged();

        #endregion

    }

    #endregion

}
