# SQL Manager 2010 Lite for MySQL 4.5.1.4
# ---------------------------------------
# Host     : localhost
# Port     : 3306
# Database : Translator


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES latin1 */;

SET FOREIGN_KEY_CHECKS=0;

CREATE DATABASE `Translator`
    CHARACTER SET 'latin1'
    COLLATE 'latin1_swedish_ci';

USE `translator`;

#
# Structure for the `translation` table : 
#

CREATE TABLE `translation` (
  `GroupControl` varchar(40) NOT NULL DEFAULT 'Default' COMMENT 'Potrebbe essere la page, o il nome della tabella a cui l''edit form fa riferimento. Rappresenta l''argomento',
  `Origin` varchar(120) NOT NULL,
  `EN` varchar(120) DEFAULT '-' COMMENT 'Il caratere di default ''-'' indica che la traduzione non è stata eseguita. Serve ad identificare che comunque la stringa da tradurre esiste ',
  `IT` varchar(120) DEFAULT '-',
  `FR` varchar(120) DEFAULT '-',
  `DE` varchar(120) DEFAULT '-',
  `ES` varchar(120) DEFAULT '-',
  `TypeControl` varchar(20) DEFAULT '-' COMMENT 'Potrebbe servire per filtrare la ricerca\r\nvalori: msgbox,text,headercol..',
  PRIMARY KEY (`Origin`,`GroupControl`),
  KEY `Origin` (`Origin`,`TypeControl`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

#
# Data for the `translation` table  (LIMIT 0,500)
#

INSERT INTO `translation` (`GroupControl`, `Origin`, `EN`, `IT`, `FR`, `DE`, `ES`, `TypeControl`) VALUES 
  ('default','Add','Add','Ins','-','-','-','btn'),
  ('default','Add Note','-','Aggiungi Nota','-','-','-','titleForm'),
  ('default','Add Step Info','Add Step info','Aggiungi Info su Step','-','-','-','titleForm'),
  ('default','Apply','-','Applica','-','-','-','btn'),
  ('default','Cancel','-','Esci','-','-','-','btn'),
  ('default','Change..','-','Cambia..','-','-','-','btn'),
  ('default','Code','Code','Codice','-','-','-',NULL),
  ('default','Confirm','Confirm','Conferma','-','-','-','label'),
  ('default','Copy','Copy','Copia','Copie','-','Copias','btn'),
  ('default','Current Job:','-','Job Corrente:','-','-','-','label'),
  ('default','DateEnd','Date End','Data Fine','-','-','-',NULL),
  ('default','DateRegistration','Date Registration','Data Registrazione','-','-','-','headercol'),
  ('default','DateStart','-','Data Inizio','-','-','-',NULL),
  ('default','Del','-','Canc','-','-','-','btn'),
  ('default','Description','-','Descrizione','-','-','-',NULL),
  ('default','DocHistoryPath','Document History','Doc Storico','-','-','-','label'),
  ('default','DocPath','Document Specification','Doc Specifica','-','-','-',NULL),
  ('default','DocSpecificationsPath','Document Specification','Doc Specifica','-','-','-','label'),
  ('default','Down','-','Giù','-','-','-','btn'),
  ('default','Exit','-','Esci','-','-','-','btn'),
  ('default','Fast Menu ','-','Menu Rapido','-','-','-','label'),
  ('default','Filter','-','Filtra','-','-','-','btn'),
  ('default','Find Notes and Docs','-','Cerca Nota','-','-','-','itemList'),
  ('default','Group','-','Gruppo','-','-','-','headercol'),
  ('default','Hide Filter','-','Nascondi Filtro','-','-','-','btn'),
  ('default','ID','-','-','-','-','-',NULL),
  ('default','IDJob','ID Job','ID Job','-','-','-','label'),
  ('default','IDProfile','ID Profile','ID Profilo','-','-','-','headercol'),
  ('default','IDUserOwner','ID Owner','ID Proprietario','-','-','-','label'),
  ('default','ImagePath','Image File','File Immagine','-','-','-','headercol'),
  ('default','Insert description about open step on your work..','-','Inserisci informazioni riguardo allo step aperto','-','-','-','message'),
  ('default','Jobs','-','-','-','-','-','itemList'),
  ('default','Language','Lang.','Lingua','-','-','-','headercol'),
  ('default','Level','-','Livello','-','-','-','headercol'),
  ('default','List of Phases','-','Lista di Fasi','-','-','-','itemList'),
  ('default','List of Steps','-','Lista di Step','-','-','-','itemList'),
  ('default','Login','-','-','-','-','-','btn'),
  ('default','Mod','Upd','Mod','-','-','-','btn'),
  ('default','Name','-','Nome','-','-','-','headercol'),
  ('default','New Password','-','Nuova Password','-','-','-','label'),
  ('default','Notes','-','Note','-','-','-','itemList'),
  ('default','Old Password','-','Vecchia Password','-','-','-','label'),
  ('default','Owner','-','Proprietario','-','-','-','headercol'),
  ('default','Page for Notes','-','Note','-','-','-','itemList'),
  ('default','Password','-','-','-','-','-','label'),
  ('default','Phase No:','-','Fase No:','-','-','-','label'),
  ('default','PhaseNo','Phase No','Fase no','-','-','-','headercol'),
  ('default','Phases','-','Fasi','-','-','-','itemList'),
  ('default','PlannedDateStart','Planned Start Date','Data Pianificata','-','-','-',NULL),
  ('default','Profile','-','Profilo','-','-','-','label'),
  ('default','ProfileName','Profile','Profilo','-','-','-','headercol'),
  ('default','Recent..','-','Recenti..','-','-','-','label'),
  ('default','Refresh','-','Aggiorna','-','-','-','btn'),
  ('default','RegistryAddress','Registry Address','Indirizzo','-','-','-','headercol'),
  ('default','RegistryName','Name','Nome','-','-','-','headercol'),
  ('default','RegistrySurname','Surname','Cognome','-','-','-','headercol'),
  ('default','Save','-','Salva','-','-','-','btn'),
  ('default','Sequence','-','No Sequenza','-','-','-','label'),
  ('default','Show Filter','-','Mostra Filtro','-','-','-','btn'),
  ('default','Start Page','-','Pagina Iniziale','-','-','-','hyperlink'),
  ('default','Status','-','Stato','-','-','-',NULL),
  ('default','StepNo','Step No','Step No','-','-','-','label'),
  ('default','Steps','-','-','-','-','-','itemList'),
  ('default','TimeHoursElapsed','Hours Elapsed','Ore Consumate','-','-','-',NULL),
  ('default','TimeHoursPlanned','Planned Hours','Ore Pianificate','-','-','-',NULL),
  ('default','Type','-','Tipo','-','-','-','headercol'),
  ('default','User','-','Utente','-','-','-','label'),
  ('default','Users','-','Utenti','-','-','-','itemList'),
  ('default','Users for job','-','Utenti Assegnati al Job','-','-','-','itemList'),
  ('default','Users for phase','-','Utenti Assegnati alla fase','-','-','-','itemList'),
  ('default','val1','Val.Param','Val.Parametro','-','-','-','label'),
  ('default','View','-','Dett','-','-','-','btn'),
  ('default','WorkGroup','Workgroup','Gruppo di Lavoro','-','-','-','headercol'),
  ('job','Code','Job Code','Codice Job','-','-','-','label'),
  ('job','DateEnd','Date End','Data Fine','-','-','-','label'),
  ('job','DateStart','-','Data Inizio','-','-','-','label'),
  ('job','Description','-','Descrizione','-','-','-','label'),
  ('job','DocPath','Document Specification','Doc Specifica Funzionale','-','-','-','label'),
  ('job','ID','-','-','-','-','-','label'),
  ('job','IDJob','ID Job','ID Job','-','-','-','headercol'),
  ('job','IDUserOwner','ID Owner','ID Proprietario','-','-','-','label'),
  ('job','Owner','-','Proprietario','-','-','-','label'),
  ('job','PlannedDateStart','Planned Date Start','Data Pianificata','-','-','-','label'),
  ('job','Sequence','-','No Sequenza','-','-','-','label'),
  ('job','Status','-','Stato','-','-','-','label'),
  ('job','StatusVal','Status Val.','Val.Stato','-','-','-','label'),
  ('job','TimeHoursElapsed','Hours Elapsed','Ore Consumate','-','-','-','label'),
  ('job','TimeHoursPlanned','Planned Hours','Ore Pianificate','-','-','-','label'),
  ('job','Type','-','Tipo','-','-','-','label'),
  ('job','val1','Val.Param','Val.Parametro','-','-','-','label'),
  ('note','Code','Job Code','Codice Job','-','-','-','label'),
  ('note','DateTimeInserted','Date of Insertion','Data Inserimento','-','-','-','label'),
  ('note','Document','Document Associated','Documento Associato','-','-','-','label'),
  ('note','ID','-','-','-','-','-','label'),
  ('note','IDUser','ID User','ID Utente','-','-','-','label'),
  ('note','IsPrivate','-','Nota Personale','-','-','-','label'),
  ('note','JobCode','Job Code','Codice Job','-','-','-','label'),
  ('note','PhaseNo','Phase No','Fase No','-','-','-','label'),
  ('note','StepNo','Step No','Step No','-','-','-','label'),
  ('note','Text','-','Testo','-','-','-','label'),
  ('note','Title','-','Titolo','-','-','-','label'),
  ('note_key','idNote','ID Note','ID Nota','-','-','-','label'),
  ('note_key','Level','-','Livello','-','-','-','label'),
  ('note_key','Name','-','Nome','-','-','-','label'),
  ('PageJobs','Code','-','Codice','-','-','-','headercol'),
  ('PageJobs','DateEnd','Date End','Data Fine','-','-','-','headercol'),
  ('PageJobs','DateStart','-','Data Inizio','-','-','-','headercol'),
  ('PageJobs','Description','-','Descrizione','-','-','-','headercol'),
  ('PageJobs','DocPath','Document Specification','Doc Specifica','-','-','-','headercol'),
  ('PageJobs','ID','-','-','-','-','-','headercol'),
  ('PageJobs','IDUserOwner','ID Owner','ID Proprietario','-','-','-','headercol'),
  ('PageJobs','Owner','-','Proprietario','-','-','-','headercol'),
  ('PageJobs','PlannedDateStart','Planned Date Start','Data Pianificata','-','-','-','headercol'),
  ('PageJobs','Sequence','-','No Sequenza','-','-','-','headercol'),
  ('PageJobs','Status','-','Stato','-','-','-','headercol'),
  ('PageJobs','StatusVal','Status Val','Val.Stato','-','-','-','headercol'),
  ('PageJobs','TimeHoursElapsed','Hours Elapsed','Ore Consumate','-','-','-','headercol'),
  ('PageJobs','TimeHoursPlanned','Planned Hours','Ore Pianificate','-','-','-','headercol'),
  ('PageJobs','Type','-','Tipo','-','-','-','headercol'),
  ('PageJobs','val1','Val.Param','Val.Parametro','-','-','-','headercol'),
  ('PageJobUsers','dateregistration','Date Registration','Data Registrazione','-','-','-','headercol'),
  ('PageJobUsers','Group','-','Gruppo','-','-','-','headercol'),
  ('PageJobUsers','id','ID','ID','-','-','-','headercol'),
  ('PageJobUsers','language','Lang.','Lingua','-','-','-','headercol'),
  ('PageJobUsers','name','Name User','Nome Utente','-','-','-','headercol'),
  ('PageJobUsers','registryname','Name','Nome','-','-','-','headercol'),
  ('PageJobUsers','registrysurname','Surname','Cognome','-','-','-','headercol'),
  ('PageJobUsers','status','Status','Stato','-','-','-','headercol'),
  ('PageJobUsers','timehoursplanned','Planned Hours','Ore Pianificate','-','-','-','headercol'),
  ('PageJobUsers','workgroup','Workgroup','Gruppo di Lavoro','-','-','-','headercol'),
  ('PageNote','DateTimeInserted','Date of Insertion','Data Inserimento','-','-','-','headercol'),
  ('PageNote','Document','-','Documento','-','-','-','headercol'),
  ('PageNote','ID','-','-','-','-','-','headercol'),
  ('PageNote','IDUser','ID User','ID Utente','-','-','-','headercol'),
  ('PageNote','IsPrivate','-','Nota Personale','-','-','-','headercol'),
  ('PageNote','JobCode','Job Code','Codice Job','-','-','-','headercol'),
  ('PageNote','PhaseNo','Phase No','Fase No','-','-','-','headercol'),
  ('PageNote','Text','-','Testo','-','-','-','headercol'),
  ('PageNote','Title','-','Titolo','-','-','-','headercol'),
  ('PageParameters','Active','-','Attivo','-','-','-','headercol'),
  ('PageParameters','Description','-','Descrizione','-','-','-','headercol'),
  ('PageParameters','GroupParam','Param Group','Gruppo del Parametro','-','-','-','headercol'),
  ('PageParameters','Name','Name','Nome','-','-','-','headercol'),
  ('PageParameters','SpecialHandling','Special Handling','Campo Speciale','-','-','-','headercol'),
  ('PageParameters','TypeVal','Type Val.','Val.Tipo','-','-','-','headercol'),
  ('PageParameters','Val1','Val.Param','Val.Parametro','-','-','-','headercol'),
  ('PageParameters','Val2','Val2 Param','Val.2°Parametro','-','-','-','headercol'),
  ('PagePhaseUsers','dateregistration','Date Registration','Data Registrazione','-','-','-','headercol'),
  ('PagePhaseUsers','Group','-','Gruppo','-','-','-','headercol'),
  ('PagePhaseUsers','id','ID','ID','-','-','-','headercol'),
  ('PagePhaseUsers','language','Lang.','Lingua','-','-','-','headercol'),
  ('PagePhaseUsers','name','Name','Nome','-','-','-','headercol'),
  ('PagePhaseUsers','registryname','Name','Nome','-','-','-','headercol'),
  ('PagePhaseUsers','registrysurname','Surname','Cognome','-','-','-','headercol'),
  ('PagePhaseUsers','status','Status','Stato','-','-','-','headercol'),
  ('PagePhaseUsers','timehoursplanned','Planned Hours','Ore Pianificate','-','-','-','headercol'),
  ('PagePhaseUsers','workgroup','Workgroup','Gruppo di Lavoro','-','-','-','headercol'),
  ('parameter','Active','-','Attivo','-','-','-','label'),
  ('parameter','Description','-','Descrizione','-','-','-','label'),
  ('parameter','GroupParam','Param Group','Gruppo del Paramtro','-','-','-','label'),
  ('parameter','Name','-','Nome','-','-','-','label'),
  ('parameter','SpecialHandling','Special Handling','Campo Speciale','-','-','-','label'),
  ('parameter','TypeVal','Type Val.','Val.Tipo','-','-','-','label'),
  ('parameter','Val1','Val.Param','Val.Parametro','-','-','-','label'),
  ('parameter','Val2','Val2 Param','Val.2°Parametro','-','-','-','label'),
  ('phase','Code','-','Codice','-','-','-','label'),
  ('phase','DateEnd','Date End','Data Fine','-','-','-','label'),
  ('phase','DateStart','-','Data Inizio','-','-','-','label'),
  ('phase','Description','-','Descrizione','-','-','-','label'),
  ('phase','DocHistoryPath','Document History','Doc Storico','-','-','-','label'),
  ('phase','DocSpecificationsPath','Document Specification','Doc Specifica','-','-','-','label'),
  ('phase','IDJob','ID Job','ID Job','-','-','-','label'),
  ('phase','PhaseNo','Phase No','Fase No','-','-','-','label'),
  ('phase','Status','-','Stato','-','-','-','label'),
  ('phase','TimeHoursElapsed','Hours Elapsed','Ore Consumate','-','-','-','label'),
  ('phase','TimeHoursPlanned','Planned Hours','Ore Pianificate','-','-','-','label'),
  ('step','Code','-','Codice Job','-','-','-','label'),
  ('step','DateEnd','Date End Step','Data Fine Step','-','-','-','label'),
  ('step','DateStart','-','Data Inizio','-','-','-','label'),
  ('step','Description','-','Descrizione','-','-','-','label'),
  ('step','IDJob','ID Job','ID Job','-','-','-','label'),
  ('step','Name','-','Nome Utente','-','-','-','label'),
  ('step','PhaseNo','Phase No','Fase No','-','-','-','label'),
  ('step','StepNo','Step No','Step No','-','-','-','label'),
  ('user','DateRegistration','Date Registration','Data Registrazione','-','-','-','headercol'),
  ('user','id','ID','ID','-','-','-','headercol'),
  ('user','IDProfile','ID Profile','ID Profilo','-','-','-','headercol'),
  ('user','ImagePath','Image File','File Immagine','-','-','-','headercol'),
  ('user','Language','Lang.','Lingua','-','-','-','headercol'),
  ('user','Level','-','Livello','-','-','-','headercol'),
  ('user','Name','-','Nome','-','-','-','headercol'),
  ('user','ProfileName','Profile','Profilo','-','-','-','headercol'),
  ('user','RegistryAddress','Registry Addrress','Indirizzo','-','-','-','headercol'),
  ('user','RegistryName','Name','Nome','-','-','-','headercol'),
  ('user','RegistrySurname','Surname','Cognome','-','-','-','headercol'),
  ('user','Status','-','Stato','-','-','-','headercol'),
  ('user','WorkGroup','Workgroup','Gruppo di Lavoro','-','-','-','headercol');
COMMIT;



/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;